### ISSUE TITLE
Upgrade to Django 2.2

### ISSUE THREAD

**Issue by janeeisenstein** [simplworld/simpl-games-api#15]
The Django 1.11 LTS support ends April 2020. We need to upgrade to Django 2.2, which currently has mainstream support and will have LTS until April 2022.

**Comment by janeeisenstein** [comment]
@jefftriplett I did some work on the `15-django-2.0` branch that might (or might not) be useful to you. All tests relying on urls are currently commented out on that branch. Simpl-users 0.8.0 supports Django 2.0.

**Comment by jefftriplett** [comment]
@janeeisenstein that was super helpful and saved me quite a bit of time. Thank you! (PR is up btw)
