### ISSUE TITLE
Deleting a run fails

### ISSUE THREAD

**Issue by janeeisenstein** [simplworld/simpl-games-api#35]
Run simpl-games-api outside Docker.
Create a Run with Worlds in a Game (e.g. simpl-div-model create_default_env).
Restart simpl-games-api
Log into http://localhost:8100/admin/ as a super user.
Attempt to delete the Run.

The attempt fails with an exception similar to this:
<img width="866" alt="exception" src="https://user-images.githubusercontent.com/26661434/105579317-cbee6880-5d53-11eb-8e28-593eeab20e1b.png">

The error appears to originate in the new webhook handling of delete events. See attached traceback.

[traceback.txt](https://github.com/simplworld/simpl-games-api/files/5860247/traceback.txt)

**IMPORTANT CLUE**: Jane mentioned that this is easily producible if the WSGI process is restarted between Run creation and Deletion.

**Comment by janeeisenstein** [comment]
Deleting a newly created Run does not trigger this exception even when if the Run has Periods, Decisions, and Results. Deleting a Run that was created before the simpl-games-api service started does trigger this exception.

**Comment by janeeisenstein** [comment]
@frankwiles I verified that creating a POP run with simpl-games-api running outside Docker followed by deleting the run in ocalhost:8100/admin/ also does not error out. Only deleting runs created before the simpl-games-api was restarted, results in this error.

**Comment by janeeisenstein** [comment]
Deleting a simpl-calc run (without Worlds) also fails due to:
```
Exception Type: DoesNotExist at /admin/games/run/1/delete/
Exception Value: RunUser matching query does not exist.
```

**Comment by janeeisenstein** [comment]
@frankwiles this defect also occurs when simpl-games-api is run in Docker, . I'm guessing I didn't see it before because the simpl-games-api image had not been rebuilt.

[docker-keyerror.txt](https://github.com/simplworld/simpl-games-api/files/6036849/docker-keyerror.txt)

**Comment by frankwiles** [comment]
signal + property caching issue in post_delete signal.

**Comment by janeeisenstein** [comment]
This fix needs more work. After applying the listeners.py and apps.py changes to the current master branch, deleting runs that were created before the games-api server was restarted works fine. However, the unit tests fail and logging out of Django admin errors out with this error:
```
AttributeError: 'Session' object has no attribute 'game'
2021-03-04 21:32:46,778 ERROR basehttp: "GET /admin/logout/ HTTP/1.1" 500 160276
ERROR:django.server:"GET /admin/logout/ HTTP/1.1" 500 160276
```

**Comment by janeeisenstein** [comment]
I fixed the edge case issues and committed to the master branch as v0.8.5.

**Comment by janeeisenstein** [comment]
Travis tests pass too.
